Potato are cool
SpikeViper/The-Powder-Toy pull request #8
Opened 2021-09-28 03:54 UTC by ridge4mama

gives life to bio because potatoes are cool.

2021-09-28 03:56 UTC, ridge4mama commented
Potato patato

2024-10-10 14:08 UTC, SlothScript requested changes
Fix the quotes and fix some formatting issues.

2024-10-10 14:08 UTC, SlothScript commented on Potato
> +	Name = "Pota
missing end quote (")

2024-10-10 14:08 UTC, SlothScript commented on Potato
> +
Does nothing

2025-07-19 00:07 UTC, closed without merging